language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
install: true
script: mvn verify
before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy
  skip_cleanup: true
  on:
    tags: true
