language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
install: true
script: mvn verify jacoco:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  - provider: script
    script: mvn deploy
    on:
      tags: true
  - provider: script
    script: mvn site-deploy
    on:
      branch: master
