language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
install: true
script: mvn verify
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
