on:
  push:
    tags: '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1.0.1
        with:
          java-version: 1.8
      - run: mvn --settings .maven/settings.xml deploy
        env:
          BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}